spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: ${MAIL_PORT:465}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
